---
 - hosts: all
   become: yes
   remote_user: ansible
   become_method: sudo
   gather_facts: no
   connection: ssh
   tasks:
    - name: add group
      group:
        name: student_ni_sir
        gid: 2021
        state: present
    - name: add user
      user: 
        name: Parman
        comment: "Privileged User"
        uid: 2022
        group: student_ni_sir
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
