---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes
  - name: install python3 debian_Ubuntu
    apt:
      name: python3
      state: latest 
  - name: install pip
    apt:
      name: pip
      state: latest
      

